-- MySQL Script generated by MySQL Workbench
-- 07/08/14 10:29:02
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema group1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `group1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `group1` ;

-- -----------------------------------------------------
-- Table `group1`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`USER` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `numberId` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `midname` VARCHAR(45) NULL,
  `phone1` VARCHAR(20) NULL,
  `phone2` VARCHAR(20) NULL,
  `location1` VARCHAR(45) NULL,
  `location2` VARCHAR(45) NULL,
  `email1` VARCHAR(45) NULL,
  `email2` VARCHAR(45) NULL,
  `passwordExpirationTime` INT NULL,
  `userStatus` INT NULL,
  `loginTime` DATETIME NULL,
  `lastUpdateDate` DATETIME NULL,
  `createDate` DATETIME NULL,
  `loginDisabled` BIT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `numberId_UNIQUE` (`numberId` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`ROLE` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`USER_HAS_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`USER_ROLE` (
  `URId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `roleId` INT NOT NULL,
  PRIMARY KEY (`URId`),
  INDEX `userid_idx` (`userId` ASC),
  INDEX `roleId_idx` (`roleId` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `group1`.`USER` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `roleId`
    FOREIGN KEY (`roleId`)
    REFERENCES `group1`.`ROLE` (`roleId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
